# Generated by Django 4.2.7 on 2025-05-27 09:26

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('problem_statement', wagtail.fields.RichTextField(blank=True)),
                ('explanation', wagtail.fields.RichTextField(blank=True)),
                ('content', wagtail.fields.StreamField([('paragraph', 0), ('image', 1)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
