# Generated by Django 4.2.7 on 2025-05-27 09:54

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_problempage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problempage',
            name='content',
            field=wagtail.fields.StreamField([('paragraph', 0), ('image', 1), ('code', 2), ('math', 4), ('multiple_choice', 11), ('hint', 13)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': 'Paste code here.', 'label': 'Code'}), 3: ('wagtail.blocks.TextBlock', (), {'help_text': 'Enter LaTeX math expression.', 'required': True}), 4: ('wagtail.blocks.StructBlock', [[('latex', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Enter the question.', 'required': True}), 6: ('wagtail.blocks.CharBlock', (), {'required': True}), 7: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Correct answer?', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('choice', 6), ('is_correct', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {'help_text': 'Add choices and mark the correct one(s).'}), 10: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Explanation for the answer.', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('question', 5), ('choices', 9), ('explanation', 10)]], {}), 12: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Enter a hint or explanation.', 'required': True}), 13: ('wagtail.blocks.StructBlock', [[('hint', 12)]], {})}),
        ),
    ]
