# Generated by Django 4.2.7 on 2025-12-23 21:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0)),
                ('max_streak', models.IntegerField(default=0)),
                ('lessons_completed', models.IntegerField(default=0)),
                ('problems_to_next_streak', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)])),
                ('current_energy', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('max_energy', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('last_energy_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('xp', models.IntegerField(default=0)),
                ('daily_xp', models.IntegerField(default=0)),
                ('weekly_xp', models.IntegerField(default=0)),
                ('monthly_xp', models.IntegerField(default=0)),
                ('last_xp_reset', models.DateField(blank=True, null=True)),
                ('last_weekly_reset', models.DateField(blank=True, null=True)),
                ('last_monthly_reset', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('streak', 'Streak Update'), ('league', 'League Promotion'), ('milestone', 'Milestone Achieved'), ('energy', 'Energy Update'), ('welcome', 'Welcome Message'), ('reminder', 'Reminder'), ('achievement', 'Achievement'), ('competition', 'Competition'), ('social', 'Social Interaction')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=255)),
                ('data', models.JSONField(default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'type', 'is_read'], name='api_notific_user_id_a7d1f5_idx'), models.Index(fields=['created_at'], name='api_notific_created_238c70_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('none', 'None'), ('partial', 'Partial'), ('complete', 'Complete')], default='none', max_length=10)),
                ('problems_solved', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('lesson_ids', models.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='api_dailyac_user_id_45e8a8_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
