# Generated by Django 4.2.27 on 2025-12-26 21:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('problem_attempt', 'Problem Attempt'), ('solve', 'Solve'), ('return', 'Return After Absence'), ('help', 'Help Others'), ('momentum_decay', 'Momentum Decay')], max_length=50)),
                ('xp_delta', models.IntegerField(default=0)),
                ('energy_delta', models.IntegerField(default=0)),
                ('request_id', models.UUIDField(db_index=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnergyWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy_balance', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0)])),
                ('lifetime_earned', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GamificationProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp_total', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveIntegerField(default=1)),
                ('identity', models.CharField(choices=[('explorer', 'Explorer'), ('builder', 'Builder'), ('solver', 'Solver'), ('mentor', 'Mentor')], default='explorer', max_length=50)),
                ('league', models.CharField(default='Bronze', max_length=50)),
                ('weekly_velocity', models.FloatField(default=0.0, help_text='XP earned in the last 7 days')),
            ],
        ),
        migrations.CreateModel(
            name='MomentumState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streak_count', models.FloatField(default=0.0)),
                ('state', models.CharField(choices=[('stable', 'Stable'), ('unstable', 'Unstable'), ('dormant', 'Dormant'), ('restored', 'Restored')], default='stable', max_length=20)),
                ('last_active_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='dailyactivity',
            name='api_dailyac_user_id_45e8a8_idx',
        ),
        migrations.AlterField(
            model_name='dailyactivity',
            name='problems_solved',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('achievement', 'Achievement'), ('streak', 'Streak'), ('streak_decay_warning', 'Streak Decay Warning'), ('energy_full', 'Energy Full'), ('league', 'League Update'), ('system', 'System Notification')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='streak',
            name='current_energy',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='streak',
            name='max_energy',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='streak',
            name='problems_to_next_streak',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='momentumstate',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='momentum_state', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gamificationprogress',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='energywallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='energy_wallet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
