# Generated by Django 4.2.20 on 2025-05-23 13:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyactivity',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='streak',
            name='last_energy_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dailyactivity',
            name='problems_solved',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='streak',
            name='current_energy',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='streak',
            name='max_energy',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='streak',
            name='problems_to_next_streak',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddIndex(
            model_name='dailyactivity',
            index=models.Index(fields=['user', 'date'], name='api_dailyac_user_id_45e8a8_idx'),
        ),
    ]
