# Generated by Django 4.2.20 on 2025-05-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_dailyactivity_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='streak',
            name='daily_xp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='streak',
            name='last_xp_reset',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='streak',
            name='xp',
            field=models.IntegerField(default=0),
        ),
    ]
