# Generated by Django 4.2.20 on 2025-05-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_streak_daily_xp_streak_last_xp_reset_streak_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='streak',
            name='last_monthly_reset',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='streak',
            name='last_weekly_reset',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='streak',
            name='monthly_xp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='streak',
            name='weekly_xp',
            field=models.IntegerField(default=0),
        ),
    ]
