# Generated by Django 4.2.20 on 2025-05-25 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_streak_last_monthly_reset_streak_last_weekly_reset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('streak', 'Streak Update'), ('league', 'League Promotion'), ('milestone', 'Milestone Achieved'), ('energy', 'Energy Update'), ('welcome', 'Welcome Message'), ('reminder', 'Reminder'), ('achievement', 'Achievement'), ('competition', 'Competition'), ('social', 'Social Interaction')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=255)),
                ('data', models.JSONField(default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'type', 'is_read'], name='api_notific_user_id_a7d1f5_idx'), models.Index(fields=['created_at'], name='api_notific_created_238c70_idx')],
            },
        ),
    ]
