# Generated by Django 4.2.20 on 2025-05-26 10:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streak',
            name='last_energy_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
