# Generated by Django 4.2.7 on 2025-12-23 21:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('subject_tag', models.CharField(choices=[('physics', 'Fiisigis'), ('math', 'Xisaab'), ('crypto', 'Qarsoodiga'), ('biology', 'Bayooloji'), ('chemistry', 'Kimistar'), ('history', 'Taariikh'), ('literature', 'Suugaan'), ('technology', 'Tignoolajiyada'), ('business', 'Ganacsi'), ('islamic_studies', 'Casharo Diinta'), ('ai', 'Hankhulka Macluumaadka'), ('fitness', 'Jirka iyo Caafimaadka')], max_length=50, unique=True)),
                ('icon', models.CharField(default='📚', help_text='Emoji or icon class', max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('color_code', models.CharField(default='#3B82F6', help_text='Hex color for campus theme', max_length=7)),
                ('member_count', models.PositiveIntegerField(default=0)),
                ('post_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_approval', models.BooleanField(default=False, help_text='Require admin approval to join')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campus',
                'verbose_name_plural': 'Campuses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(validators=[django.core.validators.MinLengthValidator(2)])),
                ('language', models.CharField(choices=[('so', 'Somali'), ('en', 'English'), ('ar', 'Arabic')], default='so', max_length=3)),
                ('is_approved', models.BooleanField(default=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='community.comment')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserCommunityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_points', models.PositiveIntegerField(default=0)),
                ('badge_level', models.CharField(choices=[('dhalinyaro', 'Garaad Dhalinyaro'), ('dhexe', 'Garaad Dhexe'), ('sare', 'Garaad Sare'), ('weyne', 'Garaad Weyne'), ('hogaamiye', 'Garaad Hogaamiye')], default='dhalinyaro', max_length=20)),
                ('total_posts', models.PositiveIntegerField(default=0)),
                ('total_comments', models.PositiveIntegerField(default=0)),
                ('total_likes_received', models.PositiveIntegerField(default=0)),
                ('total_likes_given', models.PositiveIntegerField(default=0)),
                ('preferred_language', models.CharField(choices=[('so', 'Somali'), ('en', 'English'), ('ar', 'Arabic')], default='so', max_length=3)),
                ('email_notifications', models.BooleanField(default=True)),
                ('mention_notifications', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='community_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Community Profile',
                'verbose_name_plural': 'User Community Profiles',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('room_type', models.CharField(choices=[('general', 'Guud'), ('study', 'Waxbarasho'), ('chat', 'Sheeko'), ('voice', 'Cod'), ('announcement', 'Ogeysiis')], default='general', max_length=20)),
                ('is_private', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('member_count', models.PositiveIntegerField(default=0)),
                ('post_count', models.PositiveIntegerField(default=0)),
                ('icon', models.CharField(default='hashtag', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='community.campus')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['campus__name', 'order', 'name'],
                'unique_together': {('campus', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('online', 'Online'), ('idle', 'Fadhi'), ('dnd', 'Ha Iwaxyeelin'), ('offline', 'Offline')], default='offline', max_length=10)),
                ('custom_status', models.CharField(blank=True, max_length=100)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presence', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(5)])),
                ('content', models.TextField(validators=[django.core.validators.MinLengthValidator(10)])),
                ('language', models.CharField(choices=[('so', 'Somali'), ('en', 'English'), ('ar', 'Arabic')], default='so', max_length=3)),
                ('post_type', models.CharField(choices=[('text', 'Qoraal'), ('question', "Su'aal"), ('announcement', 'Ogeysiis'), ('poll', 'Codbixin'), ('media', 'Sawir/Muuqaal')], default='text', max_length=15)),
                ('image', models.ImageField(blank=True, null=True, upload_to='community/posts/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube, Vimeo, etc.', null=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='community.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_pinned', '-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('attachment_url', models.URLField(blank=True, max_length=500, null=True)),
                ('attachment_type', models.CharField(blank=True, max_length=20, null=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='community.message')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='community.room')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('post', 'Post'), ('comment', 'Comment')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='community.comment')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='community.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('post_like', 'Qofka Soo Jeclaystay Qoraalkaaga'), ('comment_like', 'Qofka Soo Jeclaystay Faalladaada'), ('post_comment', 'Qofka Ka Faalleeyay Qoraalkaaga'), ('comment_reply', 'Qofka Kaa Jawaabay Faalladaada'), ('mention', 'Qofka Ku Soo Magacaabay'), ('new_campus_member', 'Xubin Cusub Campus-ka'), ('campus_announcement', 'Ogeysiis Campus')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community.campus')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community.comment')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community.post')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_community_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='community.post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CampusMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_moderator', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('posts_count', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('likes_received', models.PositiveIntegerField(default=0)),
                ('reputation_score', models.IntegerField(default=0)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='community.campus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-joined_at'],
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['room', '-created_at'], name='community_p_room_id_87b124_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['user', '-created_at'], name='community_p_user_id_49d8d3_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-last_activity'], name='community_p_last_ac_ea37d5_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['room', 'created_at'], name='community_m_room_id_fdcd67_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['user', 'content_type'], name='community_l_user_id_76d246_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['created_at'], name='community_l_created_786f0e_idx'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(condition=models.Q(('post__isnull', False)), fields=('user', 'post'), name='unique_post_like'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(condition=models.Q(('comment__isnull', False)), fields=('user', 'comment'), name='unique_comment_like'),
        ),
        migrations.AddIndex(
            model_name='communitynotification',
            index=models.Index(fields=['recipient', 'is_read'], name='community_c_recipie_d68f02_idx'),
        ),
        migrations.AddIndex(
            model_name='communitynotification',
            index=models.Index(fields=['created_at'], name='community_c_created_e26abb_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'created_at'], name='community_c_post_id_bea033_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user', '-created_at'], name='community_c_user_id_767aad_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campusmembership',
            unique_together={('user', 'campus')},
        ),
    ]
