# Generated by Django 4.2.7 on 2025-12-23 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('text', 'Qoraal'), ('voice', 'Cod'), ('announcement', 'Ogeysiis'), ('private', 'Gaar ah')], default='general', max_length=20),
        ),
    ]
