# Generated by Django 4.2.20 on 2025-07-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='subject_tag',
            field=models.CharField(choices=[('physics', 'Fiisigis'), ('math', 'Xisaab'), ('crypto', 'Qarsoodiga'), ('biology', 'Bayooloji'), ('chemistry', 'Kimistar'), ('history', 'Taariikh'), ('literature', 'Suugaan'), ('technology', 'Tignoolajiyada'), ('business', 'Ganacsi'), ('islamic_studies', 'Casharo Diinta'), ('ai', 'Hankhulka Macluumaadka'), ('fitness', 'Jirka iyo Caafimaadka')], max_length=50, unique=True),
        ),
    ]
