# Generated by Django 4.2.20 on 2025-05-19 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_email_verified_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='daily_goal_minutes',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='notification_preferences',
            field=models.JSONField(default=dict, help_text="User's notification preferences"),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='streak_charges',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='preferred_study_time',
            field=models.CharField(choices=[('morning', 'Aroorti Subaxda inta aan quraacaynayo'), ('afternoon', 'Waqtiga Nasashasha intaan Khadaynayo'), ('evening', 'Habeenki ah ka dib cashada ama Kahor intan seexanin'), ('flexible', 'Waqti kale oo maalintayda ah')], default='flexible', max_length=20),
        ),
    ]
