# Generated by Django 4.2.7 on 2025-03-19 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useronboarding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useronboarding',
            name='goal',
            field=models.CharField(default='Horumarinta xirfadaha', max_length=255),
        ),
        migrations.AlterField(
            model_name='useronboarding',
            name='learning_approach',
            field=models.CharField(default='Waxbarasho shaqsiyeed', max_length=255),
        ),
        migrations.AlterField(
            model_name='useronboarding',
            name='math_level',
            field=models.CharField(default='Bilowga', max_length=255),
        ),
        migrations.AlterField(
            model_name='useronboarding',
            name='minutes_per_day',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='useronboarding',
            name='topic',
            field=models.CharField(default='Xisaab', max_length=255),
        ),
        migrations.AlterField(
            model_name='useronboarding',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='useronboarding',
            table='user_onboarding',
        ),
    ]
