# Generated by Django 4.2.20 on 2025-07-05 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import random
import string


def generate_referral_code():
    """Generate a unique 8-character alphanumeric referral code"""
    return ''.join(random.choices(string.ascii_lowercase + string.digits, k=8))


def populate_referral_codes(apps, schema_editor):
    """Populate referral codes for existing users"""
    User = apps.get_model('accounts', 'User')
    
    # Get all users that don't have referral codes
    users_without_codes = User.objects.filter(referral_code='')
    
    for user in users_without_codes:
        # Generate a unique referral code
        while True:
            code = generate_referral_code()
            if not User.objects.filter(referral_code=code).exists():
                user.referral_code = code
                user.save()
                break


def reverse_populate_referral_codes(apps, schema_editor):
    """Reverse migration - clear referral codes"""
    User = apps.get_model('accounts', 'User')
    User.objects.all().update(referral_code='')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL),
        ),
        # Populate referral codes for existing users
        migrations.RunPython(populate_referral_codes, reverse_populate_referral_codes),
        # Now add the unique constraint
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
    ]
