# Generated by Django 4.2.7 on 2025-12-23 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Icon identifier for the achievement', max_length=255)),
                ('points_reward', models.PositiveIntegerField(default=100)),
                ('level_required', models.PositiveIntegerField(default=1)),
                ('achievement_type', models.CharField(choices=[('course_completion', 'Course Completion'), ('streak_milestone', 'Streak Milestone'), ('challenge_completion', 'Challenge Completion'), ('level_milestone', 'Level Milestone'), ('perfect_score', 'Perfect Score'), ('early_adopter', 'Early Adopter')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['level_required', 'points_reward'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=255)),
                ('in_progress', models.BooleanField(default=False)),
                ('course_ids', models.JSONField(blank=True, default=list, null=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('is_new', models.BooleanField(default=False)),
                ('progress', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('author_id', models.CharField(max_length=255)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CulturalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('event_date', models.DateField()),
                ('event_type', models.CharField(choices=[('holiday', 'Holiday'), ('celebration', 'Celebration'), ('competition', 'Competition'), ('workshop', 'Workshop')], max_length=50)),
                ('points_reward', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='DailyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('challenge_date', models.DateField(unique=True)),
                ('points_reward', models.PositiveIntegerField(default=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, help_text='Optional course to complete for the challenge', null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course')),
            ],
            options={
                'verbose_name': 'Daily Challenge',
                'verbose_name_plural': 'Daily Challenges',
                'ordering': ['-challenge_date'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('lesson_number', models.PositiveIntegerField(default=1)),
                ('estimated_time', models.PositiveIntegerField(default=10, help_text='Estimated time in minutes')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course')),
            ],
            options={
                'ordering': ['course', 'lesson_number'],
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('which', models.TextField(blank=True, help_text='Additional text field before question', null=True)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('single_choice', 'Single Choice'), ('true_false', 'True/False'), ('fill_blank', 'Fill in the Blank'), ('matching', 'Matching'), ('open_ended', 'Open Ended'), ('math_expression', 'Math Expression'), ('code', 'Coding Problem'), ('diagram', 'Diagram Problem')], max_length=20)),
                ('options', models.JSONField(blank=True, help_text='Answer options for applicable question types', null=True)),
                ('correct_answer', models.JSONField(help_text='Correct answer(s) in format appropriate for question_type')),
                ('explanation', models.TextField(blank=True, help_text='Explanation of the answer')),
                ('order', models.PositiveIntegerField(default=0)),
                ('content', models.JSONField(blank=True, default=dict, null=True)),
                ('diagram_config', models.JSONField(blank=True, default=dict)),
                ('diagrams', models.JSONField(blank=True, help_text='Multiple diagram configurations for complex problems', null=True)),
                ('img', models.URLField(blank=True, help_text='URL of an image associated with the problem', null=True)),
                ('xp', models.PositiveIntegerField(default=10, help_text='XP awarded for solving this problem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='courses.lesson')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_type', models.CharField(choices=[('points', 'Points'), ('badge', 'Badge'), ('streak', 'Streak'), ('achievement', 'Achievement'), ('challenge', 'Challenge')], max_length=20)),
                ('reward_name', models.CharField(max_length=255)),
                ('value', models.PositiveIntegerField(default=0)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards', to='courses.achievement')),
                ('challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards', to='courses.dailychallenge')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards', to='courses.course')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards', to='courses.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-awarded_at'],
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('streak_reminder', 'Streak Reminder'), ('achievement_earned', 'Achievement Earned'), ('daily_goal', 'Daily Goal Reminder'), ('league_update', 'League Update'), ('challenge_available', 'Challenge Available')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=1)),
                ('experience_points', models.PositiveIntegerField(default=0)),
                ('experience_to_next_level', models.PositiveIntegerField(default=100)),
                ('last_level_up', models.DateTimeField(auto_now=True)),
                ('clan', models.CharField(blank=True, help_text="User's clan affiliation", max_length=100, null=True)),
                ('region', models.CharField(blank=True, help_text="User's region in Somalia", max_length=100, null=True)),
                ('language_preference', models.CharField(choices=[('so', 'Somali'), ('en', 'English')], default='so', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='level', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LessonContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', 'Text Block'), ('example', 'Example Block'), ('code', 'Code Block'), ('image', 'Image Block'), ('video', 'Video Block'), ('quiz', 'Quiz Block'), ('problem', 'Problem Block')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('content', models.JSONField(blank=True, default=dict, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='courses.lesson')),
                ('problem', models.ForeignKey(blank=True, help_text='Reference to a Problem for problem-type blocks', null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.problem')),
            ],
            options={
                'verbose_name': 'Lesson Content Block',
                'verbose_name_plural': 'Lesson Content Blocks',
                'ordering': ['lesson', 'order'],
            },
        ),
        migrations.AddField(
            model_name='dailychallenge',
            name='lesson',
            field=models.ForeignKey(blank=True, help_text='Optional lesson to complete for the challenge', null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.lesson'),
        ),
        migrations.AddField(
            model_name='dailychallenge',
            name='problem',
            field=models.ForeignKey(blank=True, help_text='Optional problem to solve for the challenge', null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.problem'),
        ),
        migrations.CreateModel(
            name='CommunityContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_type', models.CharField(choices=[('content', 'Educational Content'), ('translation', 'Translation'), ('help', 'Helping Others'), ('feedback', 'Platform Feedback'), ('cultural', 'Cultural Content')], max_length=50)),
                ('description', models.TextField()),
                ('points_awarded', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('last_visited_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('problems_solved', models.PositiveIntegerField(default=0)),
                ('total_xp_earned', models.PositiveIntegerField(default=0)),
                ('streak_updated', models.BooleanField(default=False)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='courses.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Progress',
                'verbose_name_plural': 'User Progress',
                'unique_together': {('user', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='UserProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solved', models.BooleanField(default=False)),
                ('solved_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_solutions', to='courses.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solved_problems', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-solved_at'],
                'unique_together': {('user', 'problem')},
            },
        ),
        migrations.CreateModel(
            name='UserCulturalProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('points_earned', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='courses.culturalevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultural_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'event')},
            },
        ),
        migrations.CreateModel(
            name='UserChallengeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='courses.dailychallenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Challenge Progress',
                'verbose_name_plural': 'User Challenge Progress',
                'unique_together': {('user', 'challenge')},
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to='courses.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'achievement')},
            },
        ),
        migrations.CreateModel(
            name='SolutionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_steps', to='courses.problem')),
            ],
            options={
                'ordering': ['problem', 'order'],
                'unique_together': {('problem', 'order')},
            },
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('time_period', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('all_time', 'All Time')], max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leaderboard Entry',
                'verbose_name_plural': 'Leaderboard Entries',
                'unique_together': {('user', 'time_period')},
            },
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which hints are revealed')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='courses.problem')),
            ],
            options={
                'ordering': ['problem', 'order'],
                'unique_together': {('problem', 'order')},
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('progress_percent', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'course')},
            },
        ),
    ]
