# Generated by Django 4.2.20 on 2025-04-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='img',
            field=models.URLField(blank=True, help_text='URL of an image associated with the problem', null=True),
        ),
        migrations.AlterField(
            model_name='lessoncontentblock',
            name='content',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
