# Generated by Django 4.2.27 on 2025-12-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='community_description',
            field=models.TextField(blank=True, help_text='Description for community section'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_community_enabled',
            field=models.BooleanField(default=False, help_text='Enable community posts for this category'),
        ),
    ]
