# Generated by Django 4.2.20 on 2025-04-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_problem_img_alter_lessoncontentblock_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='content',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
