# Generated by Django 4.2.20 on 2025-04-19 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_userreward_userprogress_leaderboardentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='image',
            field=models.URLField(blank=True, help_text='URL to an image associated with the question', null=True),
        ),
    ]
