# Generated by Django 4.2.20 on 2025-05-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_problem_content'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='solutionstep',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='solutionstep',
            name='problem',
        ),
        migrations.AddField(
            model_name='problem',
            name='introduction_text',
            field=models.TextField(blank=True, help_text='Text to show before the question'),
        ),
        migrations.DeleteModel(
            name='Hint',
        ),
        migrations.DeleteModel(
            name='SolutionStep',
        ),
    ]
