# Generated by Django 4.2.20 on 2025-04-19 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_problem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='course_ids',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
