# Generated by Django 4.2.20 on 2025-04-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_category_course_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='module_ids',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
