# Generated by Django 4.2.20 on 2025-05-01 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_solutionstep_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='problem',
            unique_together={('lesson', 'order')},
        ),
    ]
