# Generated by Django 4.2.20 on 2025-05-01 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_problem_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='problem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userreward',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards', to='courses.course'),
        ),
        migrations.AddField(
            model_name='userreward',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards', to='courses.lesson'),
        ),
        migrations.RemoveField(
            model_name='problem',
            name='introduction_text',
        ),
        migrations.CreateModel(
            name='SolutionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_steps', to='courses.problem')),
            ],
            options={
                'ordering': ['problem', 'order'],
                'unique_together': {('problem', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which hints are revealed')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='courses.problem')),
            ],
            options={
                'ordering': ['problem', 'order'],
                'unique_together': {('problem', 'order')},
            },
        ),
    ]
