# Generated by Django 4.2.20 on 2025-04-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_module_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='lesson_ids',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
