# Generated by Django 4.2.20 on 2025-04-20 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_module_lesson_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('single_choice', 'Single Choice'), ('true_false', 'True/False'), ('fill_blank', 'Fill in the Blank'), ('matching', 'Matching'), ('open_ended', 'Open Ended'), ('math_expression', 'Math Expression'), ('code', 'Coding Problem'), ('diagrammar', 'Diagrammar Interactive')], max_length=20),
        ),
        migrations.CreateModel(
            name='DiagrammarContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagram_definition', models.JSONField(help_text='JSON definition of the diagram structure')),
                ('initial_state', models.JSONField(blank=True, help_text='Initial state of the diagram', null=True)),
                ('correct_states', models.JSONField(blank=True, help_text='Array of correct states for validation', null=True)),
                ('hints', models.JSONField(blank=True, help_text='Diagram-specific hints', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagrammar_content', to='courses.problem')),
            ],
            options={
                'verbose_name': 'Diagrammar Content',
                'verbose_name_plural': 'Diagrammar Contents',
            },
        ),
    ]
