# Generated by Django 4.2.20 on 2025-05-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_problem_unique_together_userreward_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='which',
            field=models.TextField(blank=True, help_text='Additional text field before question', null=True),
        ),
    ]
