# Generated by Django 4.2.20 on 2025-04-20 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_problem_question_type_diagrammarcontent'),
        ('courses', '0007_remove_module_add_course_to_lesson'),
    ]

    operations = [
    ]
