# Generated by Django 4.2.20 on 2025-04-20 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_merge_20250420_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practiceset',
            name='practice_type',
            field=models.CharField(choices=[('lesson', 'Lesson Practice'), ('course', 'Course Review'), ('mixed', 'Mixed Practice'), ('challenge', 'Challenge Problems')], max_length=20),
        ),
        migrations.AlterField(
            model_name='problem',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('single_choice', 'Single Choice'), ('true_false', 'True/False'), ('fill_blank', 'Fill in the Blank'), ('matching', 'Matching'), ('open_ended', 'Open Ended'), ('math_expression', 'Math Expression'), ('code', 'Coding Problem')], max_length=20),
        ),
        migrations.DeleteModel(
            name='DiagrammarContent',
        ),
    ]
