# Generated by Django 4.2.20 on 2025-05-25 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0009_usernotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('hydrogen', 'Hydrogen'), ('lithium', 'Lithium'), ('carbon', 'Carbon'), ('neon', 'Neon'), ('titanium', 'Titanium'), ('xenon', 'Xenon'), ('barium', 'Barium'), ('neodymium', 'Neodymium'), ('tungsten', 'Tungsten'), ('einsteinium', 'Einsteinium')], max_length=20, unique=True)),
                ('promotion_threshold', models.PositiveIntegerField(default=15)),
                ('stay_threshold', models.PositiveIntegerField(default=10)),
                ('demotion_threshold', models.PositiveIntegerField(default=5)),
                ('min_xp_required', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['min_xp_required'],
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='xp',
            field=models.PositiveIntegerField(default=10, help_text='XP awarded for solving this problem'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='problems_solved',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='streak_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='total_xp_earned',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solved', models.BooleanField(default=False)),
                ('solved_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_solutions', to='courses.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solved_problems', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-solved_at'],
                'unique_together': {('user', 'problem')},
            },
        ),
        migrations.CreateModel(
            name='UserLeague',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_week_points', models.PositiveIntegerField(default=0)),
                ('last_week_points', models.PositiveIntegerField(default=0)),
                ('last_week_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('streak_charges', models.PositiveIntegerField(default=0)),
                ('max_streak_charges', models.PositiveIntegerField(default=2)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='courses.league')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'league')},
            },
        ),
    ]
