# Generated by Django 4.2.20 on 2025-04-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_practiceset_practice_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessoncontentblock',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='lessoncontentblock',
            name='block_type',
            field=models.CharField(choices=[('text', 'Text Block'), ('example', 'Example Block'), ('code', 'Code Block'), ('image', 'Image Block'), ('practice', 'Practice Block'), ('video', 'Video Block'), ('quiz', 'Quiz Block')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lessoncontentblock',
            name='content',
            field=models.JSONField(default=dict),
        ),
    ]
