# Generated by Django 4.2.20 on 2025-04-21 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_lessoncontentblock_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='content',
            field=models.JSONField(default=dict, help_text='Additional content for the problem'),
        ),
        migrations.AddField(
            model_name='problem',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='courses.lesson'),
        ),
        migrations.AddField(
            model_name='problem',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
