# Generated by Django 4.2.20 on 2025-05-25 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_league_problem_xp_userprogress_problems_solved_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLeague',
        ),
    ]
