# Generated by Django 4.2.20 on 2025-04-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_problem_content_problem_lesson_problem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='diagram_config',
            field=models.JSONField(blank=True, default=dict, help_text='Configuration for interactive diagrams', null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('single_choice', 'Single Choice'), ('true_false', 'True/False'), ('fill_blank', 'Fill in the Blank'), ('matching', 'Matching'), ('open_ended', 'Open Ended'), ('math_expression', 'Math Expression'), ('code', 'Coding Problem'), ('diagram', 'Diagram Problem')], max_length=20),
        ),
    ]
