# Generated by Django 4.2.20 on 2025-05-26 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_delete_userleague'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='league',
            options={'ordering': ['min_xp']},
        ),
        migrations.RenameField(
            model_name='league',
            old_name='min_xp_required',
            new_name='min_xp',
        ),
    ]
