# Generated by Django 4.2.20 on 2025-06-15 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_update_diagram_config_layout'),
        ('courses', '0012_alter_league_options_and_more'),
    ]

    operations = [
    ]
