# Generated by Django 4.2.20 on 2025-04-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_problem_diagram_config_alter_problem_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='content',
            field=models.JSONField(default={'feedback': {'correct': '', 'incorrect': ''}, 'hints': [], 'metadata': {'concepts': [], 'prerequisites': [], 'skill': '', 'topic': ''}, 'steps': []}, help_text='Additional content for the problem'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='diagram_config',
            field=models.JSONField(blank=True, default={'animations': {'item_addition': {'duration': 300, 'easing': 'easeOut'}, 'weight_change': {'duration': 500, 'easing': 'easeInOut'}}, 'controls': [{'default': 40, 'label': 'Total Weight', 'max': 100, 'min': 0, 'name': 'weight', 'step': 1, 'type': 'slider'}, {'default': 4, 'label': 'Number of Items', 'max': 10, 'min': 1, 'name': 'items_count', 'step': 1, 'type': 'slider'}], 'interactive': True, 'parameters': {'items': [{'color': '#3498db', 'count': 4, 'size': 20, 'type': 'square'}], 'scale': {'color': '#2c3e50', 'height': 200, 'width': 300}, 'weight': 40}, 'styles': {'background': '#f8f9fa', 'font_family': 'Arial, sans-serif', 'font_size': '14px', 'text_color': '#2c3e50'}, 'type': 'scale-weight'}, help_text='Configuration for interactive diagrams', null=True),
        ),
    ]
