# Generated by Django 4.2.20 on 2025-04-21 09:15

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_problem_content_alter_problem_diagram_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='content',
            field=models.JSONField(default=courses.models.get_default_content),
        ),
        migrations.AlterField(
            model_name='problem',
            name='diagram_config',
            field=models.JSONField(blank=True, default=courses.models.get_default_diagram_config),
        ),
    ]
