# Generated by Django 4.2.20 on 2025-04-21 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_problem_content_alter_problem_diagram_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoncontentblock',
            name='problem',
            field=models.ForeignKey(blank=True, help_text='Reference to a Problem for problem-type blocks', null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.problem'),
        ),
        migrations.AlterField(
            model_name='lessoncontentblock',
            name='block_type',
            field=models.CharField(choices=[('text', 'Text Block'), ('example', 'Example Block'), ('code', 'Code Block'), ('image', 'Image Block'), ('video', 'Video Block'), ('quiz', 'Quiz Block'), ('problem', 'Problem Block')], max_length=20),
        ),
    ]
