# Generated by Django 4.2.20 on 2025-06-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_problem_diagram_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='diagram_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
