# Generated by Django 4.2.20 on 2025-04-21 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_lessoncontentblock_problem_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='practicesetproblem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='practicesetproblem',
            name='practice_set',
        ),
        migrations.RemoveField(
            model_name='practicesetproblem',
            name='problem',
        ),
        migrations.DeleteModel(
            name='PracticeSet',
        ),
        migrations.DeleteModel(
            name='PracticeSetProblem',
        ),
    ]
