# Generated by Django 4.2.20 on 2025-06-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_alter_problem_diagram_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='diagrams',
            field=models.JSONField(blank=True, help_text='Multiple diagram configurations for complex problems', null=True),
        ),
    ]
