# Generated by Django 4.2.20 on 2025-07-12 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_add_diagrams_field'),
    ]

    operations = [
        migrations.DeleteModel(
            name='League',
        ),
    ]
