# Generated by Django 4.2.20 on 2025-05-25 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('somali_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('min_xp', models.IntegerField(default=0)),
                ('order', models.IntegerField(unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='league_icons/')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserLeague',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_xp', models.IntegerField(default=0)),
                ('weekly_xp', models.IntegerField(default=0)),
                ('monthly_xp', models.IntegerField(default=0)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('current_league', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leagues.league')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
